### ISSUE TITLE
Simplify meta storage and default assignments

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#341]
Default values should never be merged for existing popups. They should only ever be called if no post meta key for the settings is detected.

Currently they are merged in reguardless of existence in popmake_get_popup_meta()

**Comment by danieliser** [comment]
Partially completed in #411.

To be done still:

- [ ] Import new popup models
- [ ] Refactor get_settings to load from single key.
- [ ] Refactor all previous get_meta() calls in the popup model to use get_settings insteadl.
- [ ] Check for any global bleed that needs to be corrected due to these changes as well.
