### ISSUE TITLE
Reorganize form integrations to reduce integration code and simplify interfaces.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#590]
Move all of these hard to maintain and separated functionalities into the popup editor directly.

#### Requirements:

- [x] Add new Form Submission Trigger #588
- [x] Add new Form Submission close option #589 
- [x] Add new Form Submission cookie event #725
- [x] Add integration support for non-ajax forms.

#### New Providers:
- [x] MC4WP
- [x] WP Forms
- [x] Caldera Forms

#### Optional (move to other issues if not done here)
- [ ] Add notice for users with existing form plugins that we support that they can manually migrate the settings for now until we build automated tools old methods will still work.

**Comment by danieliser** [comment]
@fpcorso Take a look at the optional items above, let me know what you think about them for v1.9. Should we waste the time on them for now?

None are requirements, first 2 only apply to NF, GF & CF7 where setting up open/close of the popup was done in form settings.

Those things will continue to work as is in the new version. But there will be a new unified interface in our popup editor to do it instead going forward.

All requirements are nearly done otherwise.
